# Use the official Node.js image  
FROM node as development

# Set the working directory  
WORKDIR /PrimeGrillsclient

# Copy package.json and package-lock.json  
COPY package*.json ./  

# Install dependencies  
RUN npm install  

# Copy the rest of the application  
COPY . .  

# test the app before building
RUN npm run dev

# Build the application  
# RUN npm run build  

# Production environment  
# FROM nginx:latest as production 


# Copy build output to Nginx html folder  
# COPY --from=build /PrimeGrillsclient/dist /usr/share/nginx/html
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# # Expose port  
# EXPOSE 80

# # Start Nginx  
# CMD ["nginx", "-g", "daemon off;"]  