version: '3.8'  
services:  
  PrimeGrillsclient:  
    build: ./PrimeGrillsclient
    networks:
      - PrimeGrillsFrontend_network
    container_name: primegrillsclient
    expose:  
      - '3000'
    volumes:
        - ./PrimeGrillsclient:/app
        - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

  PrimeGrillsPos:  
    build: ./PrimeGrillsPos
    networks:
      - PrimeGrillsFrontend_network
    container_name: primegrillspos
    expose:  
      - '3001'
    volumes:
        - ./PrimeGrillsPos:/app 
        - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
  PrimeGrillsAdmin:  
    build: ./PrimeGrillsAdmin
    networks:
      - PrimeGrillsFrontend_network
    container_name: primegrillsadmin
    expose:  
      - '3002'  
    volumes:
        - ./PrimeGrillsAdmin:/app
        - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
  PrimeGrillsManager:  
    build: ./PrimeGrillsManager 
    networks:
      - PrimeGrillsFrontend_network
    container_name: primegrillsmanager
    expose:  
      - '3003'
    volumes:
        - ./PrimeGrillsManager:/app
        - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always

   # Nginx for Reverse Proxy
  nginx:
    image: nginx:stable-alpine
    networks:
      - PrimeGrillsFrontend_network
    container_name: nginx_gateway
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - PrimeGrillsclient
      - PrimeGrillsPos
      - PrimeGrillsAdmin
      - PrimeGrillsManager

networks:
  PrimeGrillsFrontend_network:
    driver: bridge

volumes:
  PrimeGrills: