version: "3.8"

services:
  primegrillsclient:
    build:
      context: ./PrimeGrillsclient
      dockerfile: Dockerfile
    container_name: primegrillsclient
    networks:
      - primegrills_network
    ports:
      - "5173:5173"
    volumes:
      - ./PrimeGrillsClient:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=5173
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

  primegrillspos:
    build:
      context: ./PrimeGrillsPos
      dockerfile: Dockerfile
    container_name: primegrillspos
    networks:
      - primegrills_network
    ports:
      - "5174:5174"
    volumes:
      - ./PrimeGrillsPos:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=5174
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

  primegrillsadmin:
    build:
      context: ./PrimeGrillsAdmin
      dockerfile: Dockerfile
    container_name: primegrillsadmin
    networks:
      - primegrills_network
    ports:
      - "5175:5175"
    volumes:
      - ./PrimeGrillsAdmin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=5175
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

  primegrillsmanager:
    build:
      context: ./PrimeGrillsManagers
      dockerfile: Dockerfile
    container_name: primegrillsmanager
    networks:
      - primegrills_network
    ports:
      - "5176:5176"
    volumes:
      - ./PrimeGrillsManager:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_PORT=5176
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped


networks:
  primegrills_network:
    driver: bridge
