version: "3.8"

services:
  primegrillsclient:
    build:
      context: ./PrimeGrillsClient
      dockerfile: Dockerfile
    container_name: primegrillsclient
    ports:
      - "5173:5173"
    volumes:
      - ./PrimeGrillsClient:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

  primegrillspos:
    build:
      context: ./PrimeGrillsPos
      dockerfile: Dockerfile
    container_name: primegrillspos
    ports:
      - "5174:5174"
    volumes:
      - ./PrimeGrillsPos:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

  primegrillsadmin:
    build:
      context: ./PrimeGrillsAdmin
      dockerfile: Dockerfile
    container_name: primegrillsadmin
    ports:
      - "5175:5175"
    volumes:
      - ./PrimeGrillsAdmin:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped

  primegrillsmanager:
    build:
      context: ./PrimeGrillsManager
      dockerfile: Dockerfile
    container_name: primegrillsmanager
    ports:
      - "5176:5176"
    volumes:
      - ./PrimeGrillsManager:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    restart: unless-stopped
