# for development 

FROM python

WORKDIR /EVENTS/event_service

# Environment variables to optimize Python behavior
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat-openbsd
# RUN apt-get update && apt-get install -y netcat-traditional # legacy compatibility

# upgrade pip
RUN pip install --upgrade pip

# dependencies file 
COPY . requirements.txt /EVENTS/

# Install dependencies
#RUN pip install --no-cache-dir -r /EVENTS/requirements.txt # for production
RUN pip install -r /EVENTS/requirements.txt

# # copy entrypoint.sh
# COPY  /EVENTS/event_service/migrate.sh /EVENTS/event_service/migrate.sh
# RUN sed -i 's/\r$//'/EVENTS/event_service/migrate.sh && chmod +x /EVENTS/event_service/migrate.sh

# Copy project files
COPY . /EVENTS/event_service/

# Expose the default development port
EXPOSE 8008

# Run Django's development server
CMD ["python", "manage.py", "consume_auth_events"]

# run entrypoint.sh
# ENTRYPOINT ["/EVENTS/event_service/migrate.sh"]

# for production
#CMD ["gunicorn", "--bind", "0.0.0.0:8008", "event_service.wsgi:application"]