# for development 

FROM python

WORKDIR /EVENTS/event_service

# Environment variables to optimize Python behavior
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat-openbsd
# RUN apt-get update && apt-get install -y netcat-traditional # legacy compatibility

# upgrade pip
RUN pip install --upgrade pip

# dependencies file 
COPY  requirements.txt /EVENTS/event_service

# Install dependencies
#RUN pip install --no-cache-dir -r /EVENTS/requirements.txt # for production
RUN pip install -r /EVENTS/requirements.txt

# # copy entrypoint.sh
# COPY  /EVENTS/event_service/migrate.sh /EVENTS/event_service/migrate.sh
# RUN sed -i 's/\r$//'/EVENTS/event_service/migrate.sh && chmod +x /EVENTS/event_service/migrate.sh

# Copy project files
COPY . /EVENTS/event_service/

# Expose the default development port
EXPOSE 8003

# Run Django's development server
# CMD ["python", "manage.py", "consume_auth_events"]

# run entrypoint.sh
# ENTRYPOINT ["/EVENTS/event_service/migrate.sh"]

# Use an environment variable to switch between development and production
ARG MODE=production
ENV MODE=${MODE}

# for production
CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && if [ \"$MODE\" = 'development' ]; then python manage.py runserver 0.0.0.0:8000; else gunicorn --bind 0.0.0.0:8000 eventservice.wsgi:application; fi"]
