#version: '3.8'

services:

  auth_service:
    build: ./AUTH
    container_name: auth_service
    ports:
      - "8000:8000"
    volumes:
      - ./AUTH/auth:/AUTH/auth
    env_file:
      - ./AUTH/.env.dev
    depends_on:
      primegrillsdb:
        condition: service_healthy
    restart: on-failure

#   manager_service:
#     build: ./manager_service
#     container_name: manager_service
#     ports:
#       - "8001:8000"
#     volumes:
#       - ./manager_service:/app
#     env_file:
#       - ./manager_service/.env
#     depends_on:
#       - db

#   account_service:
#     build: ./account_service
#     container_name: account_service
#     ports:
#       - "8002:8000"
#     volumes:
#       - ./account_service:/app
#     env_file:
#       - ./account_service/.env
#     depends_on:
#       - db

  primegrillsdb:
    image: postgres:17
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: primegrills
      POSTGRES_PASSWORD: primegrills
      # POSTGRES_DB: primegrills_microservices_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./DATABASE/init.sql:/docker-entrypoint-initdb.d/init.sql # Ensure init.sql runs for database to create
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U primegrills"]
      interval: 5s
      retries: 5
      start_period: 10s
  
  

#   nginx:
#     image: nginx:latest
#     container_name: nginx_gateway
#     volumes:
#       - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - "80:80"
#     depends_on:
#       - auth_service
#       - manager_service
#       - account_service

volumes:
  pgdata:
