# Generated by Django 3.2.25 on 2025-02-05 07:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primegrillsapi', '0002_auto_20250205_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be numeric and 10-15 digits long', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
