# Generated by Django 5.1.6 on 2025-03-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('menu', '0002_delete_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
