# Generated by Django 5.1.6 on 2025-03-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_category_name_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AddField(
            model_name='category',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
