# Generated by Django 5.1.6 on 2025-03-14 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_order_customer_remove_orderitem_order_and_more'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='customers.customerorder'),
        ),
    ]
