# for devlopment 

FROM python

WORKDIR /PRODUCT/product

# Environment variables to optimize Python behavior
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install system dependencies
RUN apt-get update && apt-get install -y netcat-openbsd
# RUN apt-get update && apt-get install -y netcat-traditional # legacy compatibility

# upgrade pip
RUN pip install --upgrade pip

# dependencies file 
COPY . requirements.txt /PRODUCT/product/

# Install dependencies
#RUN pip install --no-cache-dir -r /PRODUCT/product/requirements.txt # for production
RUN pip install -r /PRODUCT/product/requirements.txt

# Copy project files
COPY . /PRODUCT/product/

# # copy entrypoint.sh
# COPY  migrate.sh /PRODUCT/product/migrate.sh
# RUN sed -i 's/\r$//' /PRODUCT/product/migrate.sh && chmod +x /PRODUCT/product/migrate.sh

# Expose the default development port
EXPOSE 8001

# Run Django's development server
# CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]

# run entrypoint.sh
# ENTRYPOINT ["/PRODUCT/product/migrate.sh"]

# for production
CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && if [ \"$MODE\" = 'development' ]; then python manage.py runserver 0.0.0.0:8000; else gunicorn --bind 0.0.0.0:8000 productservice.wsgi:application; fi"]
