# Generated by Django 5.1.6 on 2025-03-04 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='status',
            field=models.CharField(default='Inactive', max_length=10),
        ),
    ]
