# Use the official Node.js image  
FROM node AS build

# Set the working directory  
WORKDIR /PrimeGrillsManagers 

# Copy package.json and package-lock.json  
COPY package*.json ./  

# Install dependencies  
RUN npm install  --frozen-lockfile

# Copy the rest of the application  
COPY . .  

# test the app before building
# RUN npm run dev

# Build the application  
RUN npm run build  

# Production environment  
FROM nginx:stable-alpine AS production 


# Copy build output to Nginx html folder  
COPY --from=build /PrimeGrillsManagers/dist /usr/share/nginx/html


# # Expose port  
EXPOSE 80

# # Start Nginx  
CMD ["nginx", "-g", "daemon off;"]  