# Generated by Django 5.1.6 on 2025-03-06 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category_name',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
    ]
