# Generated by Django 5.1.6 on 2025-03-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.TextField(blank=True, null=True),
        ),
    ]
