# Generated by Django 5.1.6 on 2025-03-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0002_message_read_message_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-timestamp']},
        ),
    ]
