# Generated by Django 5.1.6 on 2025-03-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0003_alter_message_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at']},
        ),
    ]
