# Generated by Django 5.1.6 on 2025-03-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message_service', '0004_alter_thread_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['timestamp']},
        ),
    ]
