# Generated by Django 5.1.6 on 2025-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.IntegerField(unique=True)),
                ('category_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='QueryMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(unique=True)),
                ('category_id', models.IntegerField()),
                ('category_name', models.CharField(max_length=255)),
                ('menu_name', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('status', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
