# Generated by Django 5.1.6 on 2025-03-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_remove_order_customer_remove_orderitem_order_and_more'),
        ('pos', '0002_alter_transaction_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
