# Stage 1: Build the application
# Use the official Node.js image  
# FROM node AS build
FROM node AS development

# Set the working directory  
WORKDIR /PrimeGrillsAdmin  

# Copy package.json and package-lock.json  
COPY package*.json ./


# Install dependencies  
# RUN npm install --frozen-lockfile
RUN npm install  

# Copy the rest of the application  
COPY . .  

# test the app before building
# RUN npm run dev

# Build the application  
# RUN npm run build  

# # Stage 2: Serve the application with Nginx
# # Production environment  
# FROM nginx:stable-alpine AS production 


# # Copy build output to Nginx html folder  
# COPY --from=build /PrimeGrillsAdmin/dist /usr/share/nginx/html

# # Copy custom Nginx configuration
# # COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# # # Expose port  
# EXPOSE 80
EXPOSE 5175

# # Start Nginx  
# CMD ["nginx", "-g", "daemon off;"]  
CMD ["npm", "run", "dev", "--", "--host"]